# path config:
ckpt: "/home/brina/.cache/huggingface/hub/models--Vchitect--SEINE/snapshots/fd394e18671f986fd27eb64d827e01f6fd8e57ad/seine.pt"
pretrained_model_path: "/home/brina/.cache/huggingface/hub/models--CompVis--stable-diffusion-v1-4/snapshots/133a221b8aa7292a167afc5127cb63fb5005638b/"

# model config: 
model: UNet
num_frames: 16
image_size: [320, 480] #[240, 560]

# model speedup
use_fp16: True
enable_xformers_memory_efficient_attention: True

# sample config:
seed:
run_time: 13
cfg_scale: 8.0
sample_method: 'ddpm'
num_sampling_steps: 250
do_classifier_free_guidance: True
mask_type: "first1"
use_mask: True
